### PR TITLE
Update apa102.py

### PR DESCRIPTION
**Pull request by SasoriOlkof**
add support for more than 1024 leds

### CODE REVIEW

**Comment by SasoriOlkof** [comment]
Hi, sorry for the pull requests, now I see that does not work very well, you can help me with this problem?

**Comment by tinue** [comment]
It will take 2-3 weeks before I can have a look, sorry.

**Comment by SasoriOlkof** [comment]
ok, no rush :)
these changes also work well, but it seems that distance or defective lose some led hehe

**Comment by tinue** [comment]
As long as the +5V power is maintained, distance should not be an issue. Each LED controller essentially  puts out a "fresh" signal, so the data doesn't get weaker with distance. Power is another issue: You need a 5V supply every 200 LEDs or so. My strip consists of 3 times 144 LEDs (1 meter each). When I use just one supply, and light the entire strip "white", then the LEDs start to get a red tint at about the middle. The last LED is quite dim and very pink. I should add a power supply at every joint, I guess.
Defective ones are another issue ;) I had to surgically remove one LED and solder the strip together again because I got a weak connection in-between. But this affected the entire strip after the defective one, and not just the broken one alone.

**Comment by SasoriOlkof** [comment]
yes i connect to 5V every 0.5m (my strip it's 72 leds/m)
but hey, my problem is not software, and will watch to see what happens, now I have arround 1500 LEDs connected hehe

**Pull request closed without merging**
